dist: xenial
language: python

branches:
  except:
    - gh-pages

python:
  - '3.5'
  - '3.6'
  - '3.7'


install:
  - pipenv install --pre

script:
  - python -m crypy.desk.impl.tests

notifications:
  email: false

